/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorShowcaseRouteImport } from './routes/editor-showcase'
import { Route as IndexRouteImport } from './routes/index'

const EditorShowcaseRoute = EditorShowcaseRouteImport.update({
  id: '/editor-showcase',
  path: '/editor-showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor-showcase': typeof EditorShowcaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor-showcase': typeof EditorShowcaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor-showcase': typeof EditorShowcaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor-showcase'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor-showcase'
  id: '__root__' | '/' | '/editor-showcase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorShowcaseRoute: typeof EditorShowcaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor-showcase': {
      id: '/editor-showcase'
      path: '/editor-showcase'
      fullPath: '/editor-showcase'
      preLoaderRoute: typeof EditorShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorShowcaseRoute: EditorShowcaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
